
#Application Configuration
server:
  port: 3001
  error:
    include-message: always
    include-binding-errors: always

#To See H2 Console in Browser:
#http://localhost:3001/h2-console
#Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
      #*******************************************
      # DB
      #*******************************************
      datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        platform: h2
        username: sa
        password: sa

  #*******************************************
  # JPA/HIBERNATE
  #*******************************************
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #ESTO NO VA EN PRODUCCION
  database-platform: org.hibernate.dialect.H2Dialect
  properties:
    hibernate:
      show_sql: true
      use_sql_comments: false
      format_sql: false
  flyway:
    enabled: true
    validate-on-migrate: true
    datasources:
      default:
        locations: classpath:db/migration
logging:
  pattern:
    console: "%d{yyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
